### ISSUE TITLE
TypeError: hunt_algorithm_done() takes from 0 to 1 positional arguments but 2 were given

### ISSUE THREAD

**Issue by sas0125** [OALabs/hashdb-ida#37]
Popped up when there's more than 1 hash table that matched the hash.
````
HashDB: Hunting for a hash algorithm, please wait! Timeout: 15 seconds.
CRITICAL:root:hunt_algorithm_request errored: Traceback (most recent call last):
  File "C:/Users/sang/Downloads/IDA Pro 7.5.20.1028 SP3 Portable + All decompilers (Windows)/IDA Pro 7.5.20.1028 SP3 Portable/plugins/hashdb.py", line 333, in __wrapper
    self.__done_callback(*result)
TypeError: hunt_algorithm_done() takes from 0 to 1 positional arguments but 2 were given

ERROR: HashDB hash scan failed: Traceback (most recent call last):
  File "C:/Users/sang/Downloads/IDA Pro 7.5.20.1028 SP3 Portable + All decompilers (Windows)/IDA Pro 7.5.20.1028 SP3 Portable/plugins/hashdb.py", line 333, in __wrapper
    self.__done_callback(*result)
TypeError: hunt_algorithm_done() takes from 0 to 1 positional arguments but 2 were given

ERROR:root:Caught an unexpected exception: TypeError, raising.
Traceback (most recent call last):
  File "C:/Users/sang/Downloads/IDA Pro 7.5.20.1028 SP3 Portable + All decompilers (Windows)/IDA Pro 7.5.20.1028 SP3 Portable/plugins/hashdb.py", line 333, in __wrapper
    self.__done_callback(*result)
TypeError: hunt_algorithm_done() takes from 0 to 1 positional arguments but 2 were given
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\sang\AppData\Local\Programs\Python\Python37\Lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:/Users/sang/Downloads/IDA Pro 7.5.20.1028 SP3 Portable + All decompilers (Windows)/IDA Pro 7.5.20.1028 SP3 Portable/plugins/hashdb.py", line 385, in run
    super().run()
  File "C:\Users\sang\AppData\Local\Programs\Python\Python37\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/sang/Downloads/IDA Pro 7.5.20.1028 SP3 Portable + All decompilers (Windows)/IDA Pro 7.5.20.1028 SP3 Portable/plugins/hashdb.py", line 344, in __wrapper
    raise exception
  File "C:/Users/sang/Downloads/IDA Pro 7.5.20.1028 SP3 Portable + All decompilers (Windows)/IDA Pro 7.5.20.1028 SP3 Portable/plugins/hashdb.py", line 333, in __wrapper
    self.__done_callback(*result)
TypeError: hunt_algorithm_done() takes from 0 to 1 positional arguments but 2 were given
````

**Comment by anthonyprintup** [comment]
Hi, thanks for reporting the bug.
Could you please provide the sample you used when using the plugin so that we can try to trace your steps?
You can upload it to malshare or just comment with the hash.
Thanks in advance.

**Comment by sas0125** [comment]
I tried to follow this video: https://www.youtube.com/watch?v=3FPY4cLaELU&list=LL&index=2&t=1091s the sample I used is the third one in that video, this: 22d7d67c3af10b1a37f277ebabe2d1eb4fd25afbd6437d4377400e148bcc08d6

**Comment by anthonyprintup** [comment]
> I tried to follow this video: https://www.youtube.com/watch?v=3FPY4cLaELU&list=LL&index=2&t=1091s the sample I used is the third one in that video, this: 22d7d67c3af10b1a37f277ebabe2d1eb4fd25afbd6437d4377400e148bcc08d6

Hi, I believe this issue should be fixed in my [fork](https://github.com/anthonyprintup/hashdb-ida/tree/fix-worker-callbacks), you can download hashdb.py there.
I've tested each part of the plugin on your binary and everything seems to be working.
Please attempt to reproduce the original bug, and notify us if it persists. I'll create a PR as soon as we've confirmed the bug is fixed on your end.

Thanks in advance.

**Comment by sas0125** [comment]
> > I tried to follow this video: https://www.youtube.com/watch?v=3FPY4cLaELU&list=LL&index=2&t=1091s the sample I used is the third one in that video, this: 22d7d67c3af10b1a37f277ebabe2d1eb4fd25afbd6437d4377400e148bcc08d6
> 
> Hi, I believe this issue should be fixed in my [fork](https://github.com/anthonyprintup/hashdb-ida/tree/fix-worker-callbacks), you can download hashdb.py there. I've tested each part of the plugin on your binary and everything seems to be working. Please attempt to reproduce the original bug, and notify us if it persists. I'll create a PR as soon as we've confirmed the bug is fixed on your end.
> 
> Thanks in advance.

Okay it worked now, thanks for your hard work sir. This project is epic, I'm gonna close this issue.
