### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by orchechik** [OALabs/hashdb-ida#40]
## Steps to reproduce:
1.  Just placed the script at the plugins and ran refresh nothing special

## Stack trace:
```
{"user_data": {"platform": "win32", "python_version": "3.8.2", "plugin_version": "1.8.0", "ida": {"kernel_version": "7.6", "bits": 32}}, "exception_data": {"exception_type": "UnboundLocalError", "exception_value": "local variable 'algorithms' referenced before assignment"}, "frames": [{"frame_index": 2, "line_number": 570, "function_name": "OnBtnRefresh", "line": "sorted_algorithms = sorted(algorithms, key = lambda algorithm: algorithm[0].lower())", "locals": {"self": "<__plugins__hashdb.hashdb_settings_t object at 0x000002BA20DAA2B0>", "code": "0", "api_url": "'https://hashdb.openanalysis.net'"}}]}
```

## Error Log
```
  bytes   pages size description
--------- ----- ---- --------------------------------------------
   524288    64 8192 allocating memory for b-tree...
   278528    34 8192 allocating memory for virtual array...
   262144    32 8192 allocating memory for name pointers...
-----------------------------------------------------------------
  1064960            total memory allocated

Loading processor module C:\Program Files\IDA Pro 7.6\procs\pc.dll for metapc...Initializing processor module metapc...OK
Loading type libraries...
Autoanalysis subsystem has been initialized.
....

  Please check the Edit/Plugins menu for more informaton.
================================================================================
   _   _           _    ____________ 
  | | | |         | |   |  _  \ ___ \ 
  | |_| | __ _ ___| |__ | | | | |_/ /
  |  _  |/ _` / __| '_ \| | | | ___ \ 
  | | | | (_| \__ \ | | | |/ /| |_/ /
  \_| |_/\__,_|___/_| |_|___/ \____/ 


HashDB v1.8.0 by @herrcore

HashDB search shortcut key is Alt+`
================================================================================
No saved HashDB configuration
---------------------------------------------------------------------------------------
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] 
IDAPython v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------
ERROR: HashDB API request failed: HTTPSConnectionPool(host='hashdb.openanalysis.net', port=443): Max retries exceeded with url: /hash (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)')))
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 237, in 'calling callback function'
  File "C:\Program Files\IDA Pro 7.6\python\3\ida_kernwin.py", line 9792, in helper_cb
    r = self.handler(button_code)
  File "C:/Program Files/IDA Pro 7.6/plugins/hashdb.py", line 570, in OnBtnRefresh
    sorted_algorithms = sorted(algorithms, key = lambda algorithm: algorithm[0].lower())
UnboundLocalError: local variable 'algorithms' referenced before assignment
ERROR: HashDB API request failed: HTTPSConnectionPool(host='hashdb.openanalysis.net', port=443): Max retries exceeded with url: /hash (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)')))
HashDB settings saved
HashDB: HashDB terminated...
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 237, in 'calling callback function'
  File "C:\Program Files\IDA Pro 7.6\python\3\ida_kernwin.py", line 9792, in helper_cb
    r = self.handler(button_code)
  File "C:/Program Files/IDA Pro 7.6/plugins/hashdb.py", line 570, in OnBtnRefresh
    sorted_algorithms = sorted(algorithms, key = lambda algorithm: algorithm[0].lower())
UnboundLocalError: local variable 'algorithms' referenced before assignment
HashDB configuration cancelled!
```

**Comment by orchechik** [comment]
I guess it has something to do with my HTTPS connection

**Comment by orchechik** [comment]
Worked once i disabled my VPN
